version: '3.8'
services:
  nginx:
    build:
      context: docker/images/nginx
    container_name: phptools_nginx
    volumes:
      - './docker/images/nginx/conf.d:/etc/nginx/conf.d'
      - './public:/var/www/public'
    ports:
      - 80:80
    links:
      - php

  php:
    build:
      context: docker/images/php
    container_name: phptools_php
    volumes:
      - './public:/var/www/public'
      - './docker/logs/php:/var/log/php/'
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    links:
      - mysql
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway

  redis:
    build:
      context: docker/images/redis
    container_name: phptools_redis
    volumes:
      - ./docker/storage/redis:/root/redis
    restart: always
    ports:
      - "63791:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  mysql:
    image: mysql:9
    container_name: phptools_mysql
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=qwerty"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=qwerty"
      - "MYSQL_DATABASE=app"
    ports:
      - 33061:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phptools_phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=qwerty
      - UPLOAD_LIMIT=64M
    restart: always
    ports:
      - 8081:80